# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\umk54\OneDrive\Masaüstü\PenguinsDatasetAnalysis\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 722)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-color: rgb(242, 235, 229);}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalFrame_2 = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame_2.setStyleSheet("#verticalFrame_2{\n"
"background-color: rgb(202, 209, 206);\n"
"border-radius:7px;}")
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.verticalFrame_2)
        self.label_3.setStyleSheet("border-radius:5px;min-height: 30px;\n"
"color:rgb(242, 235, 229);\n"
"background-color: rgb(111, 114, 117);")
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_4.setStretch(0, 5)
        self.horizontalLayout_4.setStretch(1, 20)
        self.horizontalLayout_4.setStretch(2, 75)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.comboBox = QtWidgets.QComboBox(self.verticalFrame_2)
        self.comboBox.setStyleSheet("background-color: rgb(195, 150, 95);\n"
"border-radius:2px;\n"
"min-height: 30px;color: rgb(19, 19, 19);\n"
"color: rgb(242, 235, 229);")
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtCurrent)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_5.addWidget(self.comboBox)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 96)
        self.horizontalLayout_5.setStretch(2, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.label_4 = QtWidgets.QLabel(self.verticalFrame_2)
        self.label_4.setStyleSheet("border-radius:5px;min-height: 30px;\n"
"color:rgb(242, 235, 229);\n"
"background-color: rgb(111, 114, 117);")
        self.label_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.horizontalLayout_6.setStretch(0, 5)
        self.horizontalLayout_6.setStretch(1, 20)
        self.horizontalLayout_6.setStretch(2, 75)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalFrame_2)
        self.comboBox_2.setStyleSheet("background-color: rgb(195, 150, 95);\n"
"border-radius:2px;\n"
"min-height: 30px;color: rgb(19, 19, 19);\n"
"color: rgb(242, 235, 229);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_7.addWidget(self.comboBox_2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.horizontalLayout_7.setStretch(0, 2)
        self.horizontalLayout_7.setStretch(1, 96)
        self.horizontalLayout_7.setStretch(2, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem13)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.label_5 = QtWidgets.QLabel(self.verticalFrame_2)
        self.label_5.setStyleSheet("border-radius:5px;min-height: 30px;\n"
"color:rgb(242, 235, 229);\n"
"background-color: rgb(111, 114, 117);")
        self.label_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem15)
        self.horizontalLayout_9.setStretch(0, 5)
        self.horizontalLayout_9.setStretch(1, 20)
        self.horizontalLayout_9.setStretch(2, 75)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem16)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem17)
        self.comboBox_4 = QtWidgets.QComboBox(self.verticalFrame_2)
        self.comboBox_4.setStyleSheet("background-color: rgb(195, 150, 95);\n"
"border-radius:2px;\n"
"min-height: 30px;color: rgb(19, 19, 19);\n"
"color: rgb(242, 235, 229);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.horizontalLayout_10.addWidget(self.comboBox_4)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem18)
        self.horizontalLayout_10.setStretch(0, 2)
        self.horizontalLayout_10.setStretch(1, 96)
        self.horizontalLayout_10.setStretch(2, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem19)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem20)
        self.label_6 = QtWidgets.QLabel(self.verticalFrame_2)
        self.label_6.setStyleSheet("border-radius:5px;min-height: 30px;\n"
"color:rgb(242, 235, 229);\n"
"background-color: rgb(111, 114, 117);")
        self.label_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem21)
        self.horizontalLayout_8.setStretch(0, 5)
        self.horizontalLayout_8.setStretch(1, 20)
        self.horizontalLayout_8.setStretch(2, 75)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem22)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem23)
        self.comboBox_3 = QtWidgets.QComboBox(self.verticalFrame_2)
        self.comboBox_3.setStyleSheet("background-color: rgb(195, 150, 95);\n"
"border-radius:2px;\n"
"min-height: 30px;color: rgb(19, 19, 19);\n"
"color: rgb(242, 235, 229);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_11.addWidget(self.comboBox_3)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem24)
        self.horizontalLayout_11.setStretch(0, 2)
        self.horizontalLayout_11.setStretch(1, 96)
        self.horizontalLayout_11.setStretch(2, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem25)
        self.label = QtWidgets.QLabel(self.verticalFrame_2)
        self.label.setStyleSheet("border-radius:5px;min-height: 30px;\n"
"color:rgb(242, 235, 229);\n"
"background-color: rgb(111, 114, 117);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem26)
        self.horizontalLayout_14.setStretch(0, 5)
        self.horizontalLayout_14.setStretch(1, 20)
        self.horizontalLayout_14.setStretch(2, 75)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem27)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem28)
        self.comboBox_5 = QtWidgets.QComboBox(self.verticalFrame_2)
        self.comboBox_5.setStyleSheet("background-color: rgb(195, 150, 95);\n"
"border-radius:2px;\n"
"min-height: 30px;color: rgb(19, 19, 19);\n"
"color: rgb(242, 235, 229);")
        self.comboBox_5.setObjectName("comboBox_5")
        self.horizontalLayout_15.addWidget(self.comboBox_5)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem29)
        self.horizontalLayout_15.setStretch(0, 2)
        self.horizontalLayout_15.setStretch(1, 96)
        self.horizontalLayout_15.setStretch(2, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.verticalLayout_6.setStretch(0, 15)
        self.verticalLayout_6.setStretch(1, 2)
        self.verticalLayout_6.setStretch(2, 15)
        self.verticalLayout_6.setStretch(3, 2)
        self.verticalLayout_6.setStretch(4, 15)
        self.verticalLayout_6.setStretch(5, 2)
        self.verticalLayout_6.setStretch(6, 15)
        self.verticalLayout_6.setStretch(7, 2)
        self.verticalLayout_6.setStretch(12, 15)
        self.verticalLayout_6.setStretch(13, 2)
        self.verticalLayout_6.setStretch(14, 15)
        self.horizontalLayout_3.addWidget(self.verticalFrame_2)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem30)
        self.verticalFrame_5 = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame_5.setStyleSheet("#verticalFrame_5{\n"
"background-color: rgb(202, 209, 206);\n"
"border-radius:7px;}")
        self.verticalFrame_5.setObjectName("verticalFrame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem31)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalFrame_5)
        self.pushButton_4.setStyleSheet("background-color: rgb(195, 150, 95);\n"
"border-radius:5px;\n"
"min-height:30px;color: rgb(242, 235, 229);")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_16.addWidget(self.pushButton_4)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem32)
        self.horizontalLayout_16.setStretch(0, 2)
        self.horizontalLayout_16.setStretch(1, 96)
        self.horizontalLayout_16.setStretch(2, 2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem33)
        self.label_2 = QtWidgets.QLabel(self.verticalFrame_5)
        self.label_2.setStyleSheet("border-radius:5px;min-height: 30px;\n"
"color:rgb(242, 235, 229);\n"
"background-color: rgb(111, 114, 117);")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_18.addWidget(self.label_2)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem34)
        self.horizontalLayout_18.setStretch(0, 2)
        self.horizontalLayout_18.setStretch(1, 96)
        self.horizontalLayout_18.setStretch(2, 2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_18)
        self.verticalLayout_2.addLayout(self.verticalLayout_9)
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem35)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem36)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalFrame_5)
        self.checkBox_2.setStyleSheet("QCheckBox{\n"
"min-height: 30px;\n"
"color: rgb(30, 43, 58);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"background-color: rgb(30, 43, 58);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"background-color: rgb(242, 235, 229);\n"
"}")
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_19.addWidget(self.checkBox_2)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem37)
        self.horizontalLayout_19.setStretch(0, 5)
        self.horizontalLayout_19.setStretch(1, 50)
        self.horizontalLayout_19.setStretch(2, 45)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        spacerItem38 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem38)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem39)
        self.checkBox = QtWidgets.QCheckBox(self.verticalFrame_5)
        self.checkBox.setStyleSheet("QCheckBox{\n"
"min-height: 30px;\n"
"color: rgb(30, 43, 58);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"background-color: rgb(30, 43, 58);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"background-color: rgb(242, 235, 229);\n"
"}")
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_20.addWidget(self.checkBox)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem40)
        self.horizontalLayout_20.setStretch(0, 5)
        self.horizontalLayout_20.setStretch(1, 50)
        self.horizontalLayout_20.setStretch(2, 45)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        spacerItem41 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem41)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem42)
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalFrame_5)
        self.checkBox_3.setStyleSheet("QCheckBox{\n"
"min-height: 30px;\n"
"color: rgb(30, 43, 58);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"background-color: rgb(30, 43, 58);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"background-color: rgb(242, 235, 229);\n"
"}")
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_21.addWidget(self.checkBox_3)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem43)
        self.horizontalLayout_21.setStretch(0, 5)
        self.horizontalLayout_21.setStretch(1, 50)
        self.horizontalLayout_21.setStretch(2, 45)
        self.verticalLayout_3.addLayout(self.horizontalLayout_21)
        spacerItem44 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem44)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem45)
        self.checkBox_4 = QtWidgets.QCheckBox(self.verticalFrame_5)
        self.checkBox_4.setStyleSheet("QCheckBox{\n"
"min-height: 30px;\n"
"color: rgb(30, 43, 58);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"background-color: rgb(30, 43, 58);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"background-color: rgb(242, 235, 229);\n"
"}")
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_22.addWidget(self.checkBox_4)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem46)
        self.horizontalLayout_22.setStretch(0, 5)
        self.horizontalLayout_22.setStretch(1, 50)
        self.horizontalLayout_22.setStretch(2, 45)
        self.verticalLayout_3.addLayout(self.horizontalLayout_22)
        spacerItem47 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem47)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem48)
        self.checkBox_5 = QtWidgets.QCheckBox(self.verticalFrame_5)
        self.checkBox_5.setStyleSheet("QCheckBox{\n"
"min-height: 30px;\n"
"color: rgb(30, 43, 58);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"background-color: rgb(30, 43, 58);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"background-color: rgb(242, 235, 229);\n"
"}")
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_23.addWidget(self.checkBox_5)
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem49)
        self.horizontalLayout_23.setStretch(0, 5)
        self.horizontalLayout_23.setStretch(1, 50)
        self.horizontalLayout_23.setStretch(2, 45)
        self.verticalLayout_3.addLayout(self.horizontalLayout_23)
        self.verticalLayout_3.setStretch(0, 18)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(2, 18)
        self.verticalLayout_3.setStretch(3, 2)
        self.verticalLayout_3.setStretch(4, 18)
        self.verticalLayout_3.setStretch(5, 2)
        self.verticalLayout_3.setStretch(6, 18)
        self.verticalLayout_3.setStretch(7, 2)
        self.verticalLayout_3.setStretch(8, 20)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem50 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem50)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem51 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem51)
        self.comboBox_6 = QtWidgets.QComboBox(self.verticalFrame_5)
        self.comboBox_6.setStyleSheet("background-color: rgb(195, 153, 101);\n"
"border-radius:2px;\n"
"min-height: 30px;color: rgb(242, 235, 229);")
        self.comboBox_6.setObjectName("comboBox_6")
        self.horizontalLayout_2.addWidget(self.comboBox_6)
        spacerItem52 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem52)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 96)
        self.horizontalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem53 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem53)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem54 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem54)
        self.pushButton = QtWidgets.QPushButton(self.verticalFrame_5)
        self.pushButton.setStyleSheet("background-color: rgb(195, 150, 95);\n"
"border-radius:5px;\n"
"min-height:30px;color: rgb(242, 235, 229);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_17.addWidget(self.pushButton)
        spacerItem55 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem55)
        self.horizontalLayout_17.setStretch(0, 2)
        self.horizontalLayout_17.setStretch(1, 96)
        self.horizontalLayout_17.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        spacerItem56 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem56)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem57 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem57)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalFrame_5)
        self.pushButton_2.setStyleSheet("background-color: rgb(111, 114, 117);\n"
"border-radius:5px;\n"
"min-height:30px;color: rgb(242, 235, 229);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_24.addWidget(self.pushButton_2)
        spacerItem58 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem58)
        self.horizontalLayout_24.setStretch(0, 2)
        self.horizontalLayout_24.setStretch(1, 96)
        self.horizontalLayout_24.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_24)
        self.verticalLayout_2.setStretch(0, 28)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.setStretch(2, 38)
        self.verticalLayout_2.setStretch(3, 2)
        self.verticalLayout_2.setStretch(4, 9)
        self.verticalLayout_2.setStretch(5, 2)
        self.verticalLayout_2.setStretch(6, 9)
        self.verticalLayout_2.setStretch(7, 2)
        self.verticalLayout_2.setStretch(8, 9)
        self.horizontalLayout_3.addWidget(self.verticalFrame_5)
        spacerItem59 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem59)
        self.horizontalFrame_3 = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame_3.setStyleSheet("#horizontalFrame_3{\n"
"\n"
"background-color: rgb(54, 74, 96);\n"
"border-radius:7px;}")
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalLayout_12.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_3.addWidget(self.horizontalFrame_3)
        self.horizontalLayout_3.setStretch(0, 27)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 27)
        self.horizontalLayout_3.setStretch(3, 1)
        self.horizontalLayout_3.setStretch(4, 44)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem60 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem60)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalFrame_7 = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame_7.setStyleSheet("#horizontalFrame_7{border-radius:7px;\n"
"\n"
"background-color: rgb(54, 74, 96);}")
        self.horizontalFrame_7.setObjectName("horizontalFrame_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalFrame_7)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalFrame_3 = QtWidgets.QFrame(self.horizontalFrame_7)
        self.verticalFrame_3.setStyleSheet("#verticalFrame_3{border-radius:7px;\n"
"background-color: rgb(54, 74, 96);}\n"
"")
        self.verticalFrame_3.setObjectName("verticalFrame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_7.addLayout(self.verticalLayout_11)
        self.horizontalLayout_13.addWidget(self.verticalFrame_3)
        self.verticalFrame_4 = QtWidgets.QFrame(self.horizontalFrame_7)
        self.verticalFrame_4.setStyleSheet("#verticalFrame_4{\n"
"background-color: rgb(54, 74, 96);\n"
"border-radius:7px;}")
        self.verticalFrame_4.setObjectName("verticalFrame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalFrame_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_8.addLayout(self.verticalLayout_10)
        self.verticalLayout_8.setStretch(0, 80)
        self.horizontalLayout_13.addWidget(self.verticalFrame_4)
        self.horizontalLayout_13.setStretch(0, 80)
        self.horizontalLayout_13.setStretch(1, 20)
        self.horizontalLayout.addWidget(self.horizontalFrame_7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 49)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 50)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        spacerItem61 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem61, 1, 0, 1, 1)
        spacerItem62 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem62, 2, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 98)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 98)
        self.gridLayout.setRowStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
